credentials:
  usernames:
    yasmim.malta@allugator.com:
      email: yasmim.malta@allugator.com
      name: Yasmim Malta
      password: $2b$12$ozqGx4sW19IoPqx.liJiQec/LwaJbQBJOAcyTssqm/yOVCA64/gqm
    admin@allugator.com:
      email: admin@allugator.com
      name: Admin Allu
      password: $2b$12$uvOFbl2M4/ihxXxkAwKJDe.YYQvFhoGnXb76vjCMziaRUjOMPKe1e

cookie:
  expiry_days: 30
  key: allu_pricing_engine_secret_key_2026
  name: allu_pricing_auth

pre-authorized:
  emails:
    - yasmim.malta@allugator.com
    - admin@allugator.com
